package: d2u_helper
version: '1.6.1'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_helper

page:
    title: 'translate:d2u_helper_meta_title'
    perm: d2u_helper[]
    icon: rex-icon fa-cubes
    subpages:
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, perm: d2u_helper[settings] }
        modules: { title: 'translate:d2u_helper_meta_modules', icon: rex-icon rex-icon-module, perm: d2u_helper[settings] }
        templates: { title: 'translate:d2u_helper_meta_templates', icon: rex-icon rex-icon-template, perm: d2u_helper[settings] }
        help:
            icon: rex-icon rex-icon-help
            perm: d2u_helper[]
            title: 'translate:d2u_helper_help'
            subpages:
                readme: { title: 'translate:d2u_helper_help_chapter_readme' }
                update: { title: 'translate:d2u_helper_help_chapter_update' }
                changelog: { title: 'translate:d2u_helper_help_chapter_changelog' }