package: d2u_helper
version: '1.2.5'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_helper

page:
    title: 'translate:d2u_helper_meta_title'
    perm: d2u_helper[]
    icon: rex-icon fa-cubes
    subpages:
        modules: { title: 'translate:d2u_helper_meta_modules', icon: rex-icon rex-icon-module }
        templates: { title: 'translate:d2u_helper_meta_templates', icon: rex-icon rex-icon-template }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system }
        help:
            icon: rex-icon rex-icon-help
            title: 'translate:d2u_helper_help'
            subpages:
                readme: { title: 'translate:d2u_helper_help_chapter_readme' }
                update: { title: 'translate:d2u_helper_help_chapter_update' }
                changelog: { title: 'translate:d2u_helper_help_chapter_changelog' }

requires:
    redaxo: '>=5.1.0'
    php:
        version: '>=5.5'