package: d2u_helper
version: '1.9.4'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_helper

page:
    title: 'translate:d2u_helper_meta_title'
    perm: 'd2u_helper[]'
    icon: rex-icon fa-cubes
    subpages:
        modules: { title: 'translate:d2u_helper_meta_modules', icon: rex-icon rex-icon-module, perm: 'd2u_helper[settings]' }
        templates: { title: 'translate:d2u_helper_meta_templates', icon: rex-icon rex-icon-template, perm: 'd2u_helper[settings]' }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, perm: 'd2u_helper[settings]' }
        help:
            icon: rex-icon rex-icon-help
            title: 'translate:d2u_helper_help'
            itemclass: pull-right
            subpages:
                readme: { title: 'translate:d2u_helper_help_chapter_readme' }
                update: { title: 'translate:d2u_helper_help_chapter_update' }
                changelog: { title: 'translate:d2u_helper_help_chapter_changelog' }

requires:
    php: '>=7.4'
    redaxo: '>=5.10.0'
    
conflicts:
    d2u_address: '<1.2.3'
    d2u_courses: '<3.2.5'
    d2u_guestbook: '<1.1.0'
    d2u_history: '<1.0.2'
    d2u_immo: '<1.1.7'
    d2u_jobs: '<1.2.4'
    d2u_machinery: '<1.4.1'
    d2u_news: '<1.1.5'
    d2u_references: '<1.0.9'
    d2u_staff: '<1.1.2'

default_config:
    article_color_h: '#ffba23'
    article_color_bg: '#ffffff'
    article_color_box: '#eeeeee'
    footer_color_bg: '#4e4e4e'
    footer_color_box: '#a7a7a7'
    include_menu: 'none'
    include_menu_show: 'sm'
    include_module: 'true'
    navi_color_bg: '#ffba23'
    navi_color_font: '#ffffff'
    navi_color_hover_bg: '#ffffff'
    navi_color_hover_font: '#4e4e4e'
    show_breadcrumbs: 'true'
    subhead_color_bg: '#4e4e4e'
    subhead_color_font: '#ffffff'
    subhead_include_articlename: 'true'
        
installer_ignore:
    - .github